apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    ports:
    - containerPort: 80

#  Perform a create and validate the YAML
# kubectl create -f nginx.pod.yml --dry-run --validate=true

## Use apply instead of creat = 
# kubectl apply -f nginx.pod.yml --dry-run --validate=true

# kubectl edit -f [filename]
# kubectl exec [pod-name] -it sh
# kubectl delete pod [podname]